apiVersion: batch/v1
kind: Job
metadata:
  name: ewps-k8s-stage-input-data
spec:
  template:
    spec:
      containers:
      - name: ewps-k8s-stage-input-data
        image: alpine
        imagePullPolicy: IfNotPresent
        command:
        - "sh"
        - "-c"
        - "rm -rf /ewps/app/*; sleep 1000000"
        volumeMounts:
        - mountPath: /ewps/app
          name: nfs-pvc
          subPath: ewps-k8s
      restartPolicy: OnFailure
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: testing-storage
